# Header

menu:
  主页: /
  教程: /tags/教程
  随笔: /tags/随笔

# SubNav
subnav:
  github: "https://github.com/XVCoder"
  #weibo: "http://weibo.com/xnu132"
  #rss: "#"
  #zhihu: "#"
  #qq: "#"
  #weixin: "#"
  #jianshu: "#"
  #douban: "#"
  #segmentfault: "#"
  #bilibili: "#"
  #acfun: "#"
  mail: "mailto:xiongyu132@163.com"
  #facebook: "#"
  #google: "#"
  #twitter: "#"
  #linkedin: "#"

rss: /atom.xml

# 是否需要修改 root 路径
# 如果您的网站存放在子目录中，例如 http://yoursite.com/blog，
# 请将您的 url 设为 http://yoursite.com/blog 并把 root 设为 /blog/。
root:

# Content

# 文章太长，截断按钮文字
excerpt_link: more
# 文章卡片右下角常驻链接，不需要请设置为false
show_all_link:  '全 文'
# 数学公式
mathjax: false
# 是否在新窗口打开链接
open_in_new: false

# 打赏
# 请在需要打赏的文章的md文件头部，设置属性reward: true

# 打赏基础设定：0-关闭打赏； 1-文章对应的md文件里有reward:true属性，才有打赏； 2-所有文章均有打赏
reward_type: 0
# 打赏wording
reward_wording: '谢谢你请我吃糖果'
# 支付宝二维码图片地址，跟你设置头像的方式一样。比如：/assets/img/alipay.jpg
alipay: /assets/img/alipay.png
# 微信二维码图片地址
weixin: /assets/img/weixin.png

# 目录
# 目录设定：0-不显示目录； 1-文章对应的md文件里有toc:true属性，才有目录； 2-所有文章均显示目录
toc: 1
# 根据自己的习惯来设置，如果你的目录标题习惯有标号，置为true即可隐藏hexo重复的序号；否则置为false
toc_hide_index: true
# 目录为空时的提示
toc_empty_wording: '目录？想要的话就去找吧，我把一切都放在那里了！'

# 是否有快速回到顶部的按钮
top: true

# Miscellaneous
baidu_analytics: '290e0dafa60bf03c90ca9dec8cb52cd6'
google_analytics: 'UA-103099421-1'
favicon: /assets/img/favicon.png

#你的头像url
avatar: /assets/blogImg/Xn_U.png

#是否开启分享
share_jia: false

#评论：1、多说；2、网易云跟帖；3、畅言；4、Disqus；5友言；6、livere；7、Gitment
#不需要使用某项，直接设置值为false，或注释掉
#具体请参考wiki：https://github.com/litten/hexo-theme-yilia/wiki/

#1、多说
duoshuo: false

#2、网易云跟帖
wangyiyun: false  #原主题自带模块  不可用  原因未知

#3、畅言
changyan_appid: 'cyt3J48ER'
changyan_conf: '383b05e2ea26b74d70b17613a12190cd'

#4、Disqus 在hexo根目录的config里也有disqus_shortname字段，优先使用yilia的
disqus: false

#5、Gitment
gitment_owner: false      #你的 GitHub ID
gitment_repo: false          #存储评论的 repo
gitment_oauth:
  client_id: false           #client ID
  client_secret: false       #client secret

# 样式定制 - 一般不需要修改，除非有很强的定制欲望…
style:
  # 头像上面的背景颜色
  header: '#282C34'
  # 原本的背景色：#4d4d4d

  # 右滑板块背景
  slider: 'linear-gradient(200deg,#a0cfe4,#384454)'
  #原参数：'linear-gradient(200deg,#a0cfe4,#e8c37e)'

# slider的设置
slider:
  # 是否默认展开tags板块
  showTags: false

# 智能菜单
# 如不需要，将该对应项置为false
# 比如
#smart_menu:
#  friends: false
smart_menu:
  innerArchive: '所有文章'
  friends: '推荐'
  aboutme: '关于我'

# 网易云音乐插件
music:
  enable: true
  #id: 1070556  # 网易云分享的ID
  id: 464448450
  autoplay: true  # 是否开启自动播放

friends:
  wiki: http://wiki.solutionx.top:8080
  大鱼: https://www.bbt360.ml/
  书签备份: /bookmark/bookmarks.html

aboutme: 一壶酒<br><br>一竿纶<br><br>快活如侬有几人？
